#:kivy 1.10.0

<MyWidget@GridLayout>:
    cols:2
    id:my_widget

    FileChooserListView:
        id:filechooser
        on_selection:my_widget.selected(filechooser.selection)

    Image:
        id:image
        source:""

    Button:
        text: "Send selected image to processor"
        size_hint: 0.2, 0.05
        pos_hint: {"x": 0.4, "y": 0.01}
        on_press: my_widget.send_image_to_processor(filechooser.selection[0])